### ISSUE TITLE
Syntax highlighting for setext-style headers

### ISSUE THREAD

**Issue by mjnaderi** [ShadowKyogre/mikidown#47]
Hello,

I tried using setext-style headers, but the editor didn't highlight it:

![screenshot from 2015-07-02 01-13-48](https://cloud.githubusercontent.com/assets/2115303/8464487/b915986c-2057-11e5-8a10-88fb850aa8ac.png)

Is it planned to add this feature?

Thanks

**Comment by ShadowKyogre** [comment]
It's definitely planned to add this feature, though it may rely on some of the work that'd need to be done to also fix #38.

This is because the highlighter currently acts... weirdly... with things
~~~
**
that
**
~~~
are like what's in the previous code block I just put in this comment. 

The screenshots in the referenced issue should help explain what's going on with the current highlighter code without diving too much into a technical explanation. That being said, I can also type out a technical explanation of what's going on with the current highlighter code.
