### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by pedromorgan** [ShadowKyogre/mikidown#61]
So slick pick is cool (whaw)
Can't find slickpicker, falling back to QLineEdit for editing mikidown colors

I think Qt has a color picker xplatform, so can look at that one

So maybe we need to use that instead,, 
FINALLY after all these years Qt does it doh.. even windows had it................

**Comment by pedromorgan** [comment]
QT5

**Comment by ShadowKyogre** [comment]
Qt5's color picker isn't crappy nowadays? O_o Can I see screens? My main beefs with the Qt5 colorpicker was that it didn't allow inputting hexadecimal colors directly.

(which lead to me making things like that slickpicker and a compound widget with a button just to show color preview in this other app I have)

**Comment by pedromorgan** [comment]
OK U sold me on those comments..
And standard coporate colors in widget etc.. and lets make it simple.. ;-)))

**Comment by pedromorgan** [comment]
NOTE: 
Colors are good in tabs, eg 
- pink ones are client
- blue ones are the XXX..

We we kinda want client to use this also..
eg
red = fire
green = med
blue = police

and other domains........

**Comment by ShadowKyogre** [comment]
Oooh. So the color picker ideally would be designed to put preconfigured colors up front and then custom colors if needed?

Sorry if it seems confusing to me. Because it looks like that we'd probably need two different color pickers (which isn't hard to code up). One for the text highlighting config, and one for the "domains". (wherever that'd be in the future)

**Comment by ShadowKyogre** [comment]
Reason why I'm saying that is that the color picker with a "domain" palette would likely need to be differently coded than one just to fix up the highlighter scheme to cooperate with an unusual GUI colorscheme (like mine).

**Comment by pedromorgan** [comment]
We need to make decisions for users..
 oen of them is this "color design".. things..

Check this and make sense..
http://colorschemedesigner.com/

We present pallete..

**Comment by ShadowKyogre** [comment]
@pedromorgan: Well that I know __that__. But the reason why I put the color picker in the highlighting configuration is because those color decisions were hard-coded before. That drastically decreases usability for people who don't have black text on white background themes.

Anyway, I think I get what you're saying now. We could use something like the link you showed for all of the color picking, but only present the domain palette tab when needed?

**Comment by pedromorgan** [comment]
Check this which is what I want mikidown...
http://test.anahata-retreat.org.nz/india-retreats/

Which is a smarty.template and content is md.
and simple markdown for content..
and bootstrap css alike etc..

Cool init... 

But BUt BUt BUT my feeling is having checked others is that I want it to be..
- pluginnable to a desktop app..
- editable
- savable > to shwere ever..

I dont even want to look under the hood of the parse etc.. cos its not my talent..

**Comment by ShadowKyogre** [comment]
@pedromorgan: I think your comment was supposed to be #54 since this one's about color pickers. I'll answer you there.

**Comment by ShadowKyogre** [comment]
Closing this since this ticket's stale. And the color picker integration is working fine since slickpicker's been ported to PyQt5 along with mikidown.
